## Лабораторная работа №2

### Работа с библиотеками NumPy, pandas

<img src="https://www.freecodecamp.org/news/content/images/size/w2000/2020/09/numpy-1.png" width=200 heigth=100>


### Документация NumPy

[NumPy](https://numpy.org/)

In [2]:
import numpy as np

##Задания
#####Создайте новый файл блокнота LAB_2_Name.ipynb.

####1.	Использование команд библиотеки NumPy
*Подключите библиотеку numpy*
#####1.1.	Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5


In [3]:
my_array = np.arange(5,101,5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

##### 2.1.	Из полученного массива получить массив с кратными 10 числами

In [4]:
my_array = my_array[my_array % 10 == 0]
# my_array % 10 == 0 создаёт логический массив, где True соответствует элементам, кратным 10
# лог. массив исп-ся в качестве индексации => позволяет получить соотв-ие усл. эл-ы
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

##### 3.1.	Получить двумерный массив с двумя столбцами

 Синтаксис ```np.pad(array, (before, after), 'constant')``` означает:
* ```before``` — сколько элементов добавить в начало массива,
* ```after``` — сколько элементов добавить в конец (разница в длине между двумя массивами).

```np.column_stack((arr1, arr2))``` берёт элементы из arr1 и arr2 и складывает их по столбцам. Первый элемент arr1 будет стоять в первой строке первого столбца, первый элемент arr2 — в первой строке второго столбца, и так далее.

In [5]:
two_columns = my_array.reshape(5, 2)
two_columns

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

##### 4.1.	Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5




In [6]:
my_second_array = my_array - 5
my_second_array

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

##### 5.1. Соедините массивы, полученные в п. 1.3. и 1.4., горизонтально. Используйте .T для транспонирования матрицы.

Чтобы соединить массивы, полученные в предыдущих шагах, горизонтально и использовать .T для транспонирования в NumPy это делается с помощью функции ```np.hstack()```, которая объединяет массивы по горизонтали, и метода ```.T``` для транспонирования.

In [7]:
# Преобразую массивы в векторы-столбцы (одномерные массивы преобразуются в двумерные с одним столбцом), что необходимо для корректного объединения по горизонтали.
combined_array = np.hstack((two_columns,my_second_array.reshape(5,2)))

# Транспонирование матрицы, меняя местами строки и столбцы
transposed_array = combined_array.T

print("Горизонтально объединённый массив:")
print(combined_array)
print("\nТранспонированный массив:")
print(transposed_array)

Горизонтально объединённый массив:
[[ 10  20   5  15]
 [ 30  40  25  35]
 [ 50  60  45  55]
 [ 70  80  65  75]
 [ 90 100  85  95]]

Транспонированный массив:
[[ 10  30  50  70  90]
 [ 20  40  60  80 100]
 [  5  25  45  65  85]
 [ 15  35  55  75  95]]


##### 6.1.	Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [8]:
devided = combined_array[1:3,:4] / my_array[3]
transported_devided = devided.T
transported_devided

array([[0.75 , 1.25 ],
       [1.   , 1.5  ],
       [0.625, 1.125],
       [0.875, 1.375]])

##### 7.1.	Оставить только те значения, которые не изменились после деления

In [12]:
# Оставляем только те элементы, результат деления которых равен 1
unchanged_values = devided == 1
indices = np.argwhere(unchanged_values)
# оригинальные значения из my_array
result = combined_array[1:3, :][indices[:, 0], indices[:, 1]]

print(f"Значения, которые не изменились после деления (равны 1): {result}")

Значения, которые не изменились после деления (равны 1): [40]


##### 8.1. Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

метод ```vstack()``` (от англ. vertical stack) объед. массивы в вертикальном направлении

In [13]:
my_third_array = my_array + 5
three_arrays = np.vstack((my_second_array, my_array, my_third_array))
print(f'initial three arrays: \n{three_arrays}\n')
three_arrays[[0,2]] = three_arrays[[2,0]]
print(f'switched first and third rows in three arrays: \n{three_arrays}')

initial three arrays: 
[[  5  15  25  35  45  55  65  75  85  95]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 15  25  35  45  55  65  75  85  95 105]]

switched first and third rows in three arrays: 
[[ 15  25  35  45  55  65  75  85  95 105]
 [ 10  20  30  40  50  60  70  80  90 100]
 [  5  15  25  35  45  55  65  75  85  95]]


##### 9.1.	Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().


In [14]:
print(f'row  1: {three_arrays[[0]]}\n'
      f'average: {np.mean(three_arrays[[0]])}\n'
      f'median: {np.median(three_arrays[[0]])}\n'
      f'standard deviation: {np.std(three_arrays[[0]])}\n')

print(f'row  2: {three_arrays[[1]]}\n'
      f'average: {np.mean(three_arrays[[1]])}\n'
      f'median: {np.median(three_arrays[[1]])}\n'
      f'standard deviation: {np.std(three_arrays[[1]])}\n')

print(f'row  3: {three_arrays[[2]]}\n'
      f'average: {np.mean(three_arrays[[2]])}\n'
      f'median: {np.median(three_arrays[[2]])}\n'
      f'standard deviation: {np.std(three_arrays[[2]])}')

row  1: [[ 15  25  35  45  55  65  75  85  95 105]]
average: 60.0
median: 60.0
standard deviation: 28.722813232690143

row  2: [[ 10  20  30  40  50  60  70  80  90 100]]
average: 55.0
median: 55.0
standard deviation: 28.722813232690143

row  3: [[ 5 15 25 35 45 55 65 75 85 95]]
average: 50.0
median: 50.0
standard deviation: 28.722813232690143


##### 10.1.	Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.

Параметр ```axis=1``` указывает, что вычисление идет вдоль строк.


>**Нормализация**: делится каждый элемент строки на соответствующее максимальное значение этой строки.

In [15]:
# Нахождение максимальных значений вдоль каждой строки (axis=1)
max_values = np.max(three_arrays, axis=1)

# Нормализация по строкам: деление каждого элемента строки на её максимальное значение
normalized_array = three_arrays / max_values[:, np.newaxis]

print("Исходный массив:")
print(three_arrays)

print("\nМаксимальные значения по строкам:")
print(max_values)

print("\nНормализованный массив:")
print(normalized_array)

Исходный массив:
[[ 15  25  35  45  55  65  75  85  95 105]
 [ 10  20  30  40  50  60  70  80  90 100]
 [  5  15  25  35  45  55  65  75  85  95]]

Максимальные значения по строкам:
[105 100  95]

Нормализованный массив:
[[0.14285714 0.23809524 0.33333333 0.42857143 0.52380952 0.61904762
  0.71428571 0.80952381 0.9047619  1.        ]
 [0.1        0.2        0.3        0.4        0.5        0.6
  0.7        0.8        0.9        1.        ]
 [0.05263158 0.15789474 0.26315789 0.36842105 0.47368421 0.57894737
  0.68421053 0.78947368 0.89473684 1.        ]]


##2.	Использование команд библиотеки pandas

Подключите библиотеку pandas
##### 2.1.	Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.

In [17]:
import pandas as pd

In [19]:
df = pd.read_csv("/content/drive/MyDrive/Global Population Trends(2016-2022).csv")
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55              63      37.342       7.027   
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38              61      32.516       8.266   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[1073 rows x 12 columns]

##### Изучите полученные данные:
##### 2.2.	 Считайте несколько первых записей таблицы (head())

In [20]:
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8           3  
2                  46.3           3  
3                  44.8           3  
4                  43.4           3

##### 2.3.	 Определите размерность данного фрейма (shape())

In [21]:
df.shape

(1073, 12)

##### 2.4.	 Выведите название заголовков столбцов фрейма (columns)

In [22]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

##### 2.5.	Получите описание всех переменных (полей) (info())

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


##### 2.6.	 Удалите строки, не содержащие значения в столбце «Total Population» - “-”

```df['Total Population'] != '-'``` cоздает логическую маску, которая проверяет каждую строку в столбце ```"Total Population"```, и возвращает ```True``` для строк, где значение не равно ```"-"```.


```df[df['Total Population'] != '-']``` применяет логическую маску, фильтруя строки, где значение в столбце ```"Total Population"``` не равно ```"-"```.

In [24]:
df_cleaned = df[df['Total Population'] != '-']
df_cleaned

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

##### 2.7.	Получите описательную статистику по переменным (например, max(), min(), describe())

In [25]:
print("Описательная статистика для числовых переменных:")
df_cleaned.describe()

Описательная статистика для числовых переменных:


Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000

In [26]:
max_population = df_cleaned['Birth Rate'].max()
min_population = df_cleaned['Birth Rate'].min()

print(f"\nМаксимальное значение в 'Birth Rate': {max_population}")
print(f"Минимальное значение в 'Birth Rate': {min_population}")


Максимальное значение в 'Birth Rate': 46.127
Минимальное значение в 'Birth Rate': 0.0


##### 2.8.	Выполните сортировку данных по нескольким критериям

In [27]:
# Сортировка данных по нескольким критериям: сначала по 'Year' (по убыванию), затем по 'Birth Rate' (по возрастанию)
sorted_df = df_cleaned.sort_values(by=['Year', 'Birth Rate'], ascending=[False, True])

print("Отсортированные данные:")
print(sorted_df.head())

Отсортированные данные:
                      Country  Year Total Population Urban Population  \
18             American Samoa  2021           45,035           39,257   
22                    Andorra  2021           79,034           69,438   
629                    Monaco  2021           36,686           36,686   
713  Northern Mariana Islands  2021           49,481           45,468   
420                 Hong Kong  2021        7,413,100        7,413,100   

    Rural Population Population Density Life Expectancy  Birth Rate  \
18             5,778                  -               -         0.0   
22             9,596                  -               -         0.0   
629                -                  -               -         0.0   
713            4,013                  -               -         0.0   
420                -                  -              85         5.0   

     Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
18          0.0              -             

##### 2.9.	 Выведите название страны, которая имеет максимальную численность населения

```df_cleaned['Total Population'].str.replace(',', '').astype(float)``` удаляет запятые в числах и преобразует столбец ```'Total Population'``` в числовой формат (float).

```df_cleaned['Total Population'].idxmax()```: возвращает индекс строки с максимальным значением в столбце ```'Total Population'```.

```df_cleaned.loc[...]```: используем этот индекс, чтобы извлечь строку с максимальной численностью населения.

In [ ]:
df_cleaned['Total Population'] = df_cleaned['Total Population'].str.replace(',', '').astype(float)

In [35]:

max_population_row=df_cleaned.loc[df_cleaned['Total Population'].idxmax()]

print(f"Страна с максимальной численностью населения {max_population_row['Total Population']}: {max_population_row['Country']}")

Страна с максимальной численностью населения 1412360000.0: China


In [33]:
df_cleaned[df_cleaned['Country'] == 'China']

Country  Year  Total Population Urban Population Rural Population  \
202   China  2018      1.402760e+09      829,760,595      572,999,405   
203   China  2019      1.407745e+09      848,982,855      558,762,145   
204   China  2020      1.411100e+09      866,810,508      544,289,492   
205   China  2021      1.412360e+09      882,894,483      529,465,517   

    Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
202                149              78       10.86        7.08          1.554   
203                149              78       10.41        7.09          1.496   
204                150              78        8.52        7.07          1.281   
205                  -              78        7.52        7.18          1.164   

    Infant Mortality Rate Growth Rate  
202                   6.4           0  
203                   5.9           0  
204                   5.5           0  
205                   5.1           0

##### 2.10.	Выведите название страны, которая имеет минимальную численность населения


In [34]:
min_population_row = df_cleaned.loc[df_cleaned['Total Population'].idxmin()]

print(f"Страна с минимальной численностью населения {min_population_row['Total Population']}: {min_population_row['Country']}")

Страна с минимальной численностью населения 10865.0: Tuvalu


##### 2.11.	Экспорт фрейма в MS Excel

In [36]:
df.to_excel("laba2.xlsx", index=False, engine='openpyxl')